name: Checkout Specific Commit

on:
  workflow_dispatch:
    # Only allow these branches to be selected in "Use workflow from"
    branches:
      - 'release/*'
    inputs:
      commit_sha:
        description: 'Commit SHA to checkout'
        required: true
        type: string

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific commit
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha }}
      
      - name: Show commit info
        run: |
          echo "Checked out commit: $(git rev-parse HEAD)"
          echo "Commit message: $(git log -1 --pretty=%B)"
