name: Checkout Specific Commit

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to run the workflow'
        required: true
      commit_sha:
        description: 'Commit SHA to checkout'
        required: true
        type: string


jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific commit
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha }}
      
      - name: Show commit info
        run: |
          echo "Checked out commit: $(git rev-parse HEAD)"
          echo "Commit message: $(git log -1 --pretty=%B)"
