name: Commit Selection and Checkout

on:
  workflow_dispatch:    # This will use the branch selected in "Use workflow from"

jobs:
  list-and-select:
    runs-on: ubuntu-latest
    environment: commit-selection    # This will create a pause for approval
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: List last 10 commits
        run: |
          echo "Available commits from ${{ github.ref_name }}:"
          echo "----------------------------------------"
          git log --oneline -n 10
          echo "----------------------------------------"
          echo "Please select a commit SHA from the list above and provide it in the environment approval comments"

  checkout-commit:
    needs: list-and-select
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific commit
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha }}    # This will come from environment approval comments
      
      - name: Confirm checkout
        run: |
          echo "Successfully checked out commit: $(git rev-parse HEAD)"
          echo "Commit message: $(git log -1 --pretty=%B)"
