name: Checkout Specific Commit

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to checkout'
        required: true
        type: string

jobs:
  validate-and-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH="${{ github.ref_name }}"
          if [[ ! $BRANCH =~ ^release/.+ ]]; then
            echo "Error: Branch '$BRANCH' is not a release branch. Only release/* branches are allowed."
            exit 1
          fi
          echo "Branch validation passed: $BRANCH"

      - name: Checkout specific commit
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha }}
      
      - name: Show commit info
        run: |
          echo "Checked out commit: $(git rev-parse HEAD)"
          echo "Commit message: $(git log -1 --pretty=%B)"
